-- 1. Tabla ESTACION (Gestor de Flota / Estaciones)
CREATE TABLE ESTACION (
    id_estacion INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    capacidad_total INT NOT NULL,
    capacidad_disponible INT NOT NULL,
    CONSTRAINT pk_estacion PRIMARY KEY (id_estacion),
    CONSTRAINT chk_capacidad CHECK (capacidad_disponible >= 0 AND capacidad_disponible <= capacidad_total)
);

-- 2. Tabla VEHICULO (Gestor de Flota)
CREATE TABLE VEHICULO (
    id_vehiculo INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    codigo_qr VARCHAR(50) NOT NULL,
    tipo_vehiculo VARCHAR(20) NOT NULL,
    estado_actual VARCHAR(20) NOT NULL,
    id_estacion_actual INT,
    CONSTRAINT pk_vehiculo PRIMARY KEY (id_vehiculo),
    CONSTRAINT fk_vehiculo_estacion FOREIGN KEY (id_estacion_actual) REFERENCES ESTACION(id_estacion)
);

-- 3. Tabla RESERVACION (Gestor de Reservas)
CREATE TABLE RESERVACION (
    id_reservacion INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario VARCHAR(50) NOT NULL,
    id_vehiculo INT NOT NULL,
    fecha_hora_reserva TIMESTAMP NOT NULL,
    estado_reservacion VARCHAR(20) NOT NULL,
    CONSTRAINT pk_reservacion PRIMARY KEY (id_reservacion),
    CONSTRAINT fk_reserva_vehiculo FOREIGN KEY (id_vehiculo) REFERENCES VEHICULO(id_vehiculo)
);

-- 4. Tabla VIAJE (Gestor de Viajes)
CREATE TABLE VIAJE (
    id_viaje INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario VARCHAR(50) NOT NULL,
    id_vehiculo INT NOT NULL,
    fecha_hora_inicio TIMESTAMP,
    fecha_hora_fin TIMESTAMP,
    estado_viaje VARCHAR(20) NOT NULL,
    costo_total DECIMAL(10,2),
    CONSTRAINT pk_viaje PRIMARY KEY (id_viaje),
    CONSTRAINT fk_viaje_vehiculo FOREIGN KEY (id_vehiculo) REFERENCES VEHICULO(id_vehiculo)
);
